### ISSUE TITLE
Critical issue: Biased Shuffling

### ISSUE THREAD

**Issue by kchalkias** [adambudziak/shuffle#4]
I spotted a critical issue on the Fisher Yates shuffling logic.
Note you are currently iterating from left to right in https://github.com/adambudziak/shuffle/blob/master/src/fy.rs#L35
but then j should be between `i` and `n`, thus `i ≤ j < n`. In the current impl. it's unfortunately between `0` and `i`.

**Comment by adambudziak** [comment]
I'm not exactly sure that the change of the ordering results in a biased shuffle but I cannot find the exact source on which I based the implementation.

Certainly the results would be biased if `j` was taken from the whole range `{0, ..., n-1}` each time, but the argument for that falls when it's actually just picked from the range on the "other side" of `i`. 

However, it's quite simple to make it exactly as stated on the Wikipedia, so I'll adjust the implementation to that :+1:
