### ISSUE TITLE
Why not publish new versions to crates.io?

### ISSUE THREAD

**Issue by nanai10a** [adambudziak/shuffle#7]
I found this crate on `crates.io` but couldn't use it due to a dependency issue. And I came to see this repository.
The fix PR has already been merged and seems to be mentioned in `Cargo.toml` as a new version, but not in `crates.io`.
Will you publish the new version?

**Comment by adambudziak** [comment]
Hi, sorry for the inconvenience. I'll admit, I work on this crate so rarely that I forget about the standard way of doing things. I published the current master to crates.io as version `0.1.6`. Thanks.
